apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
# some metadata about the template itself
metadata:
  name: git-repo
  title: Git Repository
  description: Use this template to create a new Git repository
  tags: ['devops', 'azure-devops', 'git']
spec:
  owner: igoravl/backstage-templates
  type: devops

  # these are the steps which are rendered in the frontend with the form input
  parameters:
    - title: Repository Information
      required: [ name, description, gitFlow, owner]
      properties:
        name:
          title: Repository Name
          type: string
          description: Enter the name of the new Git repository. Use only letters, numbers, and hyphens.
        description:
          title: Description
          type: string
          description: Description of your project/repository.
          ui:options:
            rows: 5
        gitFlow: 
          title: Git Workflow 
          type: boolean
          description: Specify the Git workflow to be used in your repository
          ui:widget: radio
          enumNames:
            - GitFlow
            - GitHubFlow
        gitIgnore:
          title: .gitignore File
          type: string
          description: Include a standard .gitignore file in the repository?
          enum: ['Node', 'VisualStudio', 'Global/VisualStudioCode']
          enumNames: ['Node.js', 'Visual Studio', 'Visual Studio Code']
