apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: {{ cookiecutter.name }}
  title: {{ cookiecutter.title }}
  description: {{ cookiecutter.description }}
spec:
  type: service
  lifecycle: production
  owner: {{ cookiecutter.owner }}
