apiVersion: backstage.io/v1beta2
kind: Template
metadata:
  name: nodejs-express-webapi
  title: Node.js Web API with Express
  description: Use este modelo para criar um novo projeto de Web API usando Node.js com o framework Express

spec:
  owner: cloudmotionbr/backstage
  type: service

  parameters:
    - title: Preencha os campos abaixo
      required: [name, title, owner]
      properties:
        name:
          title: Nome
          type: string
          description: Nome do seu projeto. Use apenas letras, números, pontos e hífens.
          ui:autofocus: true
        title:
          title: Título
          type: string
          description: Nome amigável do seu projeto, que será exibido no README e no catálogo de componentes.
        description:
          title: Descrição
          type: string
          description: Breve descrição do seu projeto.
          ui:options:
            rows: 5
        owner:
          title: Squad
          description: O nome da squad responsável por este projeto
          type: string
          ui:field: OwnerPicker
          ui:options:
            allowedKinds: ['Group']

  steps:
    - id: fetch-code
      name: Generate code
      action: fetch:cookiecutter
      input:
        url: ./template
        values:
          name: '{{ parameters.name }}'
          title: '{{ parameters.title }}'
          description: '{{ parameters.description }}'
          owner: '{{ parameters.owner }}'

    - id: publish
      name: Publish repository
      action: publish:azure
      input:
        allowedHosts: ['dev.azure.com']
        repoUrl: 'dev.azure.com?organization=bancomodal&owner=TI&repo={{parameters.owner}}-{{parameters.name}}'

    - id: enable-build
      name: Enable CI pipeline
      action: azure:pipelines:create
      input:
        name: '{{ parameters.name }}-CI'
        repoUrl: 'dev.azure.com?organization=bancomodal&owner=TI&repo={{parameters.owner}}-{{parameters.name}}'
        sourcePath: 'azure-pipelines.yaml'

    - id: register
      name: Register component
      action: catalog:register
      input:
        repoContentsUrl: '{{ steps.publish.output.repoContentsUrl }}'
        catalogInfoPath: 'catalog-info.yaml'

    - id: queue-build
      name: Queue pipeline
      action: azure:pipelines:queue
      input:
        id: '{{ steps.enable-build.output.id }}'
        repoUrl: '{{ parameters.repoUrl }}'
